### PR TITLE
Remove tds subpackage and replace with catalog module.

### PR DESCRIPTION
**Pull request by dopplershift**
The whole library is really about talking to the TDS, so having a module about it seems redundant. Since the code that's in there is all about catalogs, move it to a `catalog.py` file.

This also merges the tests that were there, possibly addressing #10 .

### CODE REVIEW

**Comment by dopplershift** [comment]
Must have removed some covered lines when I killed the `tds/__init__.py`.  I've now adjusted the settings so that coverage needs to go down by 0.5% before it complains.

**Comment by lesserwhirls** [comment]
Looks good to me. Yes, this also addresses #10. Want to add a reference to #10 to the commit message?

**Comment by dopplershift** [comment]
I'll do it in the merge.

**Comment by lesserwhirls** [comment]
Ok, I did the merge...but why doesn't this show up as being your work (i.e. it;s listed as my commit, and looks like it counts towards my lines of code added/removed)?

**Pull request merged**
