### PR TITLE
Change line 44 to include 0123 for day instead of 012

### PR DESCRIPTION
**Pull request by pjpokran**
Fixes issue #172 so that filter_time_nearest searches for days 30 and 31 work properly.

### CODE REVIEW

**Comment by pjpokran** [comment]
Apparently I commited this with the wrong email address.. Not sure how to get around that.. I signed the CLA with my github account, but that's associated with a different email than what I commited the change with.. How can I fix this?

**Comment by dopplershift** [comment]
Try running this:
```
git commit --amend --author="Author Name <email@address.com>"
```
Then do:

```
git push —-force
```

**Comment by dopplershift** [comment]
🎉 Are you interested in trying to write a test? Otherwise, (if you don’t mind) I can knock one out real quick and push to your branch.

**Comment by pjpokran** [comment]
I'm not really sure where to start with that.. I'd appreciate it. Seeing one written, hopefully I can swing the next one. Thx!

**Comment by dopplershift** [comment]
Probably should have @lesserwhirls or @jrleeman sign off since I've now committed on this PR.

**Pull request merged**
