### PR TITLE
Modernize infrastructure

### PR DESCRIPTION
**Pull request by dopplershift**
This is bringing us up to date with what I consider "current" infrastructure:
- Use sphinx-gallery
- Build with sphinx linkcheck and warnings as errors
- Use pytest-flake8 for linting
- Use appveyor's built-in test result reporting

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Ready to be merged @dopplershift?

**Comment by dopplershift** [comment]
@lesserwhirls Was going to:

1. Install flake8-quotes and make sure the tests actually fail
2. Fix quoting

**Comment by lesserwhirls** [comment]
That works. Just let me know.

**Comment by dopplershift** [comment]
I think this is good to go now.

**Comment by lesserwhirls** [comment]
codecov is failing, but just barely (down 0.01%). I'd merge it in as is, but I don't have permissions on github to override the check.

**Pull request merged**
