### PR TITLE
Added metadata parsing to TDSCatalog object

### PR DESCRIPTION
**Pull request by lesserwhirls**
Adds the ability to parse metadata blocks from TDS Client Catalogs, and only exposes services on a dataset that are defined by the ServiceName element contained in the metadata.

### CODE REVIEW

**Comment by lesserwhirls** [comment]
address gh-#6

**Comment by lesserwhirls** [comment]
**Do not merge yet**

I want to address gh-#14 in this pull request too.

**Comment by lesserwhirls** [comment]
Ok, this should be ready for review now.

**Comment by dopplershift** [comment]
We probably need some examples using this. I won't hold it up for those, but that will be the best way to see how the API feels.

**Pull request merged**
