### PR TITLE
TDSCatalog session management

### LINKED ISSUE #279: TDSCatalog session unclosed
Within the TDScatalog, the `requests.Session()` that is created has a keep alive to ensure further quick access to the url. However, the `requests.Session()` has an issue ([by design](https://github.com/psf/requests/issues/4664)) that doesn't close the session connection when the resource is deleted. This throws a warning to the terminal when running on Ubuntu with Python 3.6.8.

`ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('10.200.28.161', 43980), raddr=('10.200.28.71', 80)>`

This is only a warning but can fill up the terminal quite quickly if lots of `TDSCatalog` objects are created. The simple solution is to add the session to the `TDSCatalog` object to allow users to close the session when needed.

### PR DESCRIPTION
**Pull request by scotthavens**
### Description Of Changes

- Added the session object to the TDSCatalog to allow for easier session management
- Added test for closing the session

#### Checklist

- [X] Closes #279
- [X] Tests added
- [X] All tests passed

### CODE REVIEW

**Review by zbruick — CHANGES_REQUESTED** [review]
Thanks for the contribution! Looks like there are a few flake8 lint issues to take care of for CI to pass (see Travis logs). I can help point them out if needed, but they should be pretty straightforward to take care of.

**Review by zbruick — APPROVED** [review]

**Review by dopplershift — APPROVED** [review]
Looks good, thanks for the contribution! If you can click through and "sign" our electronic Contributors' License Agreement (CLA), we can merge this in.

**Comment by scotthavens** [comment]
The CLA is new to me and as a federal government employee, I will have to get my employer to approve this agreement.

**Comment by scotthavens** [comment]
As a federal employee, all the work I do is in the public domain and I cannot retain the copyright to work that I do. So you are free to use this code without any restrictions but I cannot sign the CLA.

**Comment by dopplershift** [comment]
Understood. That sounds fine. Merging over the CLA checker.

**Pull request merged**
