### PR TITLE
changed lonlat_box() param order

### PR DESCRIPTION
**Pull request by jclark754**
fixes issue #48

### CODE REVIEW

**Comment by jclark754** [comment]
Why does this fail? Am I missing something? Just forked, made the quick change and made the PR.

**Comment by lesserwhirls** [comment]
Here are a few things I see:

1. From Travis-ci: siphon/http_util.py:193:91: E501 line too long (91 > 90
characters) (code style error)

2. Need to use the new API in the test (currently it is failing in
test_http_util.TestDataQuery.trst_spatial_reset2
Cheers!

Sean

**Comment by lesserwhirls** [comment]
coveralls does not seem to be working properly at the moment - everything looks good but the coverage report is just no finishing up. Given that the change was simple, I'm not going to wait for coveralls to get into gear and I'll just merge this in.

**Comment by lesserwhirls** [comment]
Didn't mean to close it without committing...my bad...

**Pull request merged**
