### PR TITLE
Upper air data exposure

### LINKED ISSUE #155: Better-expose Wyoming upper air
- Add to API docs
- Add examples
- Maybe import into `simplewebservice`?

### PR DESCRIPTION
**Pull request by jrleeman**
* Add example of upper air request from Wyoming.
* Add to API docs.

Closes #155

### CODE REVIEW

**Comment by jrleeman** [comment]
Sphinx doc build failure appears to be related to: https://github.com/sphinx-doc/sphinx/issues/4139

**Comment by dopplershift** [comment]
We need to add pandas to the example requirements.

**Comment by dopplershift** [comment]
Actually, since this is probably core functionality for siphon, it should probably go in the base requirements.

**Comment by jrleeman** [comment]
Failure of the doc build appears to be radar data related. We're hitting live data here!?

**Comment by dopplershift** [comment]
Yeah, we hit live data in the Siphon examples.

**Pull request merged**
