### PR TITLE
Added New Columns to WyomingUpperAir Module

### PR DESCRIPTION
**Pull request by apottr**
#### Description Of Changes
Added `mixing_ratio, relative_humidity, potential_temperature, equivalent_potential_temperature, virtual_potential_temperature` to `siphon.simplewebservice.wyoming`. 
#### Checklist
- [x] Tests added

### CODE REVIEW

**Comment by apottr** [comment]
Need to fix up my git before submitting.

**Comment by dopplershift** [comment]
No worries. For future reference, you can just keep pushing to the same branch (maybe needing `git push --force`) and that will update the PR.

**Comment by jmineau** [comment]
What needs to be done to get these columns added to the Wyoming web service? Happy to help.

**Comment by dopplershift** [comment]
Tweak the parsing code here to include the desired columns:
https://github.com/Unidata/siphon/blob/7c24f4003b738bd88d8bcf965b39992d1ee97c49/src/siphon/simplewebservice/wyoming.py#L70-L125

If it's adding some of the scalar columns, it's unclear to me to how to do that to a Pandas `DataFrame` easily (mixing scalars and series).

**Pull request closed without merging**
